name: Add issue to project
on:
  issues:
    types:
      - opened

jobs:
  add_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue to Cync
        uses: actions/add-to-project@v0.3.0
        with:
          project-url: 'https://github.com/orgs/FHU/projects/4'
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
